### ISSUE TITLE
Integration between dotliquid and with .NET Core

### ISSUE THREAD

**Issue by jindovu** [cloudbase/juju-powershell-modules#19]
Hi Guy,
     I'm a developer and I want delopment website using dotliquid view engine, However dotliquid doesn't support on .net core, Clould you tell me how can I do that

**Comment by gabriel-samfira** [comment]
Heya buddy :-),

At the verry bottom of this commit:

https://github.com/gabriel-samfira/dotliquid/commit/db43fd6dc3dca4811bdc365d45172399f4c6f67e

You will find a script that will build against coreCLR.

Note, I built this against the version of coreClr that comes with Windows nano server 2016 TP5. Should be the same in your case.

I also build a DLL, which you can get from:

https://github.com/cloudbase/juju-powershell-modules/tree/master/Templating/lib/netcore50

See if that works for you. Hope the upstream project will make the trivial changes to get the official project to compile nicely on coreCLR.

**Comment by jindovu** [comment]
thank you for your help

**Comment by gabriel-samfira** [comment]
My pleasure. Hope you found what you were looking for!
